language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev
      - linux-libc-dev:i386

env:
  global:
    - DEPLOY_LIBS="libbsxml-json.a libED_CSVFile.a libED_INIFile.a libED_JSONFile.a libED_MATFile.a libED_SSVFile.a libED_XLSFile.a libED_XLSXFile.a libED_XMLFile.a libexpat.a libzlib.a libparson.a"
    # BBPASS
    - secure: "QTj7LL9IODoPLwiha1ZZOkaPmgP4V9yVBJG4Z9qjm54Zv7UYHwHX1ghDN+DkzlPbNUXBBhclekmyCsxiZI9JZsYBWl84p33VrSTWD5eGQ4M6jJaXIiXk8hsStKHNfeq3FB+Bc+0R5ST0/OdyMex8sNfW9nntRbkjDT5jRdrbt/KG694dj5YvmL/E+RdLfXe6a/y3wlGXF6N/0Z9cHtP0TKgEQij/+KrGPk5qxwbAzYbT9jzmgGBbH8WHV1l8FtlVCYio7PVDswGkYgsMPn2lS3VZxOmZn5XJyYkOPQE3Fxlsr/50q2kHe4ufIX8U03upHvmW2FuXaPxar7ssAORPFIF+zKcKpCCMz6mfHgQB20tefqr2EvfTV6UJIx4pnUCJ5pzrlEBI3AQcUjQwFv0HnGeK/wiQFlny85POuoKN9V+jwUAxoXhnCZFLO2D8n4uyplvwximifEuaQ1gd835dan2ngGp0Ws6psnYC4iLJ6aULbD0EIc1aAbf3H+NF3GfqKhH4nz18eHNbd0ghMbTSvKWm2eKb9oX8anuCZtO0VO79A6lu8A86ZthnAS1dQ3J2KR7/xjug75nqlBpXHcIFB40sfl/zQntCK5SNMzGGojNWn/SGEDf7jon9esda3dtmHMo6mFNUTA/CX4E+xGjtpaafyCnOo82a/FD3wu8kjy4="

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      env:
        - PLATFORM=32
    - os: linux
      compiler: gcc-4.8
      env:
        - PLATFORM=64
    - os: linux
      compiler: clang
      env:
        - PLATFORM=64

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - curl https://bitbucket.org/Swyter/bitbucket-curl-upload-to-repo-downloads/raw/default/upload-to-bitbucket.sh -O -J -L
  - chmod +x ./upload-to-bitbucket.sh

script:
  - cd ExternData/Resources/C-Sources
  - if [[ "$PLATFORM" == "32" ]]; then make CFLAGS="-O3 -msse2 -m32 -fPIC" TARGETDIR="linux32"; fi
  - if [[ "$PLATFORM" == "64" ]]; then make CFLAGS="-O3 -fPIC"; fi
  - cd ../Library/linux$PLATFORM
  - tar cJf ExternData_linux$PLATFORM.tar.xz $DEPLOY_LIBS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]]; then sh ../../../../upload-to-bitbucket.sh tbeu $BBPASS /tbeu/downloads/downloads ExternData_linux$PLATFORM.tar.xz; fi

notifications:
  email: false
